apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l1c4l0q87-nodejs
  janus-idp.io/tekton: l1c4l0q87-nodejs
  backstage.io/kubernetes-id: l1c4l0q87-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l1c4l0q87-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
